### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by vitsh1974** [Dakword/WBSeller#3]
require_once  (__DIR__ . DIRECTORY_SEPARATOR . 'include/WBSeller/vendor/autoload.php') ;
$token = 'иииииииииииии';  // плохой или ошибка
$wbSellerAPI = new \Dakword\WBSeller\API([
    'apikey' => $token,

]);

try {
$getNewOrders = $wbSellerAPI->Marketplace()->getNewOrders();
} catch (ApiClientException $e) {
    echo "Ошибка " . $e->getCode() . ": " . $e->getMessage();
}
die;

***********************************
хотеолсь бы подавить ошибки и получить признак что ошибка

результат
<b>Fatal error</b>:  Uncaught Dakword\WBSeller\Exception\ApiClientException: invalid token in /home/wb2/public_html/wp-content/plugins/wb-prime/include/WBSeller/src/API/AbstractEndpoint.php:130
Stack trace:
#0 /home/wb2/public_html/wp-content/plugins/wb-prime/include/WBSeller/src/API/AbstractEndpoint.php(77): Dakword\WBSeller\API\AbstractEndpoint-&gt;request()
#1 /home/wb2/public_html/wp-content/plugins/wb-prime/include/WBSeller/src/API/Endpoint/Marketplace.php(260): Dakword\WBSeller\API\AbstractEndpoint-&gt;getRequest()
#2 /home/wb2/public_html/wp-content/plugins/wb-prime/wb-prime.php(32): Dakword\WBSeller\API\Endpoint\Marketplace-&gt;getNewOrders()
#3 /home/wb2/public_html/wp-settings.php(473): include_once('...')
#4 /home/wb2/public_html/wp-config.php(102): require_once('...')
#5 /home/wb2/public_html/wp-load.php(50): require_once('...')
#6 /home/wb2/public_html/wp-admin/admin.php(34): require_once('...')
#7 /home/wb2/public_html/wp-admin/index.php(10): require_once('...')
#8 {main}
  thrown in <b>/home/wb2/public_html/wp-content/plugins/wb-prime/include/WBSeller/src/API/AbstractEndpoint.php</b> on line <b>130</b><br />

***********

так же хотелось бы
что то вида
 $wbSellerAPI->Marketplace()->apiChek()

********************
ps

в общем то

решение

$token = 'и';

try {
	$wbSellerAPI = new \Dakword\WBSeller\API([
    'apikey' => $token,

]);
$getNewOrders = $wbSellerAPI->Marketplace()->getNewOrders();
} catch (\Exception  $e) {
    var_dump( $e );
}
die;

**Comment by Dakword** [comment]
Вариант использования:
```php
try {
    $wbSellerAPI = new \Dakword\WBSeller\API([
        'apikey' => '123456',
    ]);
    $newOrders = $wbSellerAPI->Marketplace()->getNewOrders();
    var_dump($newOrders);
} catch (\Dakword\WBSeller\Exception\WBSellerException $e) {
    var_dump('API response: ' . $e->getCode() . ' ' . $e->getMessage());
}
```
Не понял, что здесь "не так"?
