### ISSUE TITLE
Не определяет mime изображения

### ISSUE THREAD

**Issue by lexsmil** [Dakword/WBSeller#4]
Не удатся добавить изображения к товарам. Пробовал разные товары, разные изображения jpg/png , ответ один и тот же.
```
$photo = '/полный/путь/к/файлу.jpg';
$wbSellerAPI = new \Dakword\WBSeller\API([
    'masterkey' => 'ключ-апи'
]);

$contentApi = $wbSellerAPI->Content();
$res = $contentApi->uploadMedia($nmId, $id, $photo);
```

> array(
>    'additionalErrors' => NULL,
>    'data' => NULL,
>    'error' => true,
>    'errorText' => 'Ошибка сохранения товара: Невозможно определить mime-тип файла; поддерживаемые форматы: изображения ("image/bmp", "image/gif", "image/jpeg", "image/png", "image/webp"), видео ("video/mp4", "video/quicktime")',
> )

**Comment by Dakword** [comment]
$photo = file_get_contents('/полный/путь/к/файлу.jpg');
...
->uploadMedia($nmId, $id, $photo)
