### ISSUE TITLE
Баг при проверке errorText при запросе к статистике кампаний

### ISSUE THREAD

**Issue by aslanchevskiy** [Dakword/WBSeller#7]
https://github.com/Dakword/WBSeller/blob/d6ebe9c2b83c4e569da5c4b9f0467198246406b2/src/API/AbstractEndpoint.php#L132

`ErrorException {#4792 // app/Services/WB/Request/DigitalAdv.php:677
  #message: "Undefined property: stdClass::$errorText"
  #code: 0
  #file: "./vendor/dakword/wbseller/src/API/AbstractEndpoint.php"
  #line: 132
`

**Comment by Dakword** [comment]
Спасибо. Учтено в 4.16.1
