### ISSUE TITLE
Обращение к protected методу getRequest из класса AdvFinance

### ISSUE THREAD

**Issue by aslanchevskiy** [Dakword/WBSeller#8]
`  Error 

  Call to protected method Dakword\WBSeller\API\AbstractEndpoint::getRequest() from scope Dakword\WBSeller\API\Endpoint\Subpoint\AdvFinance

  at vendor/dakword/wbseller/src/API/Endpoint/Subpoint/AdvFinance.php:117
    113▕      * @return array
    114▕      */
    115▕     public function costs(DateTime $dateFrom, DateTime $dateTo): array
    116▕     {
  ➜ 117▕         return $this->Adv->getRequest('/adv/v1/upd', [
    118▕             'from' => $dateFrom->format('Y-m-d'),
    119▕             'to' => $dateTo->format('Y-m-d'),
    120▕         ]);
    121▕     }
`

**Comment by Dakword** [comment]
Спасибо за отчет.
Проверьте в 4.17.0
