### ISSUE TITLE
Возвращается некорректный тип данных

### ISSUE THREAD

**Issue by aslanchevskiy** [Dakword/WBSeller#9]
В последней версии:
`   TypeError 

  Dakword\WBSeller\API\Endpoint\Adv::statistic(): Return value must be of type array, stdClass returned

  at vendor/dakword/wbseller/src/API/Endpoint/Adv.php:244
    240▕      * @return array
    241▕      */
    242▕     public function statistic(array $params): array
    243▕     {
  ➜ 244▕         return $this->postRequest('/adv/v2/fullstats', $params);
    245▕     }
    246▕ 
    247▕     /**
    248▕      * Статистика по ключевым фразам

  1   app/Services/WB/Request/DigitalAdv.php:531
      Dakword\WBSeller\API\Endpoint\Adv::statistic()
`

**Comment by Dakword** [comment]
Я все вызовы оборачиваю, что и вам предлагаю.
```
  try {
      $result = $Adv->statistic([
          ['id' =>555]
      ]);
  } catch (\Throwable $exc) {
      var_dump($exc->getMessage(), $Adv->responseCode(), $this->Adv->response());
  }
```
```
string(105) "Return value of Dakword\WBSeller\API\Endpoint\Adv::statistic() must be of the type array, object returned"
int(400)
object(stdClass)#288 (1) {
  ["error"]=>
  string(132) "некорректные параметры запроса: нет кампаний с корректными интервалами"
}
```
